// Integration tests for Phase 5b (large-order uniform asymptotic expansions).
//
// Tests K, H, I, J, Y functions at large orders (fnu > fnul ~ 86)
// to exercise ZBUNK/ZUNK1/ZUNK2, ZBUNI/ZUNI1/ZUNI2, ZUNHJ paths.
//
// Reference values: tests/reference_values/phase5b_f64.json
// Generated by Fortran TOMS 644 with IEEE 754 machine constants.
//
// Tolerance: 3e-14 (same algorithm, different operation ordering
// between Fortran and Rust; large-order paths may have slightly
// more accumulated rounding differences).

use complex_bessel::types::{HankelKind, Scaling};
use complex_bessel::{besseli_seq, besselj_seq, besselk_seq, bessely_seq, hankel_seq};
use num_complex::Complex;
use serde::Deserialize;

// ── JSON schema ──

#[derive(Deserialize)]
#[allow(dead_code)]
struct RefFile {
    generator: String,
    machine: String,
    tests: Vec<RefTest>,
}

#[derive(Deserialize)]
struct RefTest {
    function: String,
    label: String,
    inputs: RefInputs,
    outputs: RefOutputs,
}

#[derive(Deserialize)]
struct RefInputs {
    z_re: f64,
    z_im: f64,
    fnu: f64,
    kode: i32,
    #[serde(default)]
    m: Option<i32>,
    n: i32,
}

#[derive(Deserialize)]
#[allow(dead_code)]
struct RefOutputs {
    nz: Option<i32>,
    ierr: Option<i32>,
    cy_re: Option<Vec<f64>>,
    cy_im: Option<Vec<f64>>,
    y_re: Option<Vec<f64>>,
    y_im: Option<Vec<f64>>,
}

// Large-order paths involve chained uniform asymptotic expansions + backward
// recurrence, which can accumulate slightly more rounding than moderate-order
// paths. The original Fortran test suite (zqcbes.f) uses 1e-12 tolerance.
const FORTRAN_TOL: f64 = 1e-13;

fn assert_complex_rel(label: &str, got: Complex<f64>, re_ref: f64, im_ref: f64, tol: f64) {
    let expected = Complex::new(re_ref, im_ref);
    let scale = expected.norm();
    if scale == 0.0 {
        assert!(
            got.re.abs() < tol && got.im.abs() < tol,
            "{label}: expected ~0, got ({}, {})",
            got.re,
            got.im
        );
        return;
    }
    let err = (got - expected).norm() / scale;
    assert!(
        err < tol,
        "{label}: relative error {err:.2e} exceeds tolerance {tol:.0e}\n  \
         expected: ({re_ref:.17e}, {im_ref:.17e})\n  \
         got:      ({:.17e}, {:.17e})",
        got.re,
        got.im,
    );
}

fn load_refs() -> RefFile {
    let json = include_str!("reference_values/phase5b_f64.json");
    serde_json::from_str(json).expect("failed to parse phase5b_f64.json")
}

// ── Test: Large-order K function (ZBUNK path) ──

#[test]
fn besk_large_order_vs_fortran() {
    let refs = load_refs();

    let tests: Vec<&RefTest> = refs
        .tests
        .iter()
        .filter(|t| t.function == "zbesk" && t.outputs.ierr == Some(0))
        .collect();

    assert!(!tests.is_empty(), "no zbesk large-order tests found");

    for t in &tests {
        let z = Complex::new(t.inputs.z_re, t.inputs.z_im);
        let fnu = t.inputs.fnu;
        let scaling = match t.inputs.kode {
            1 => Scaling::Unscaled,
            2 => Scaling::Exponential,
            _ => panic!("{}: unknown kode", t.label),
        };
        let n = t.inputs.n as usize;

        let result = besselk_seq(fnu, z, n, scaling)
            .unwrap_or_else(|e| panic!("{}: unexpected error {:?}", t.label, e));

        let cy_re = t.outputs.cy_re.as_ref().expect("missing cy_re");
        let cy_im = t.outputs.cy_im.as_ref().expect("missing cy_im");

        for j in 0..n {
            let sub = if n > 1 {
                format!("{}[{}]", t.label, j)
            } else {
                t.label.clone()
            };
            assert_complex_rel(&sub, result.values[j], cy_re[j], cy_im[j], FORTRAN_TOL);
        }
    }

    eprintln!(
        "  besk_large_order: {} test cases passed (tol={:.0e})",
        tests.len(),
        FORTRAN_TOL
    );
}

// ── Test: Large-order H function (ZBUNK via ZBESH) ──

#[test]
fn besh_large_order_vs_fortran() {
    let refs = load_refs();

    let tests: Vec<&RefTest> = refs
        .tests
        .iter()
        .filter(|t| t.function == "zbesh" && t.outputs.ierr == Some(0))
        .collect();

    assert!(!tests.is_empty(), "no zbesh large-order tests found");

    for t in &tests {
        let z = Complex::new(t.inputs.z_re, t.inputs.z_im);
        let fnu = t.inputs.fnu;
        let scaling = match t.inputs.kode {
            1 => Scaling::Unscaled,
            2 => Scaling::Exponential,
            _ => panic!("{}: unknown kode", t.label),
        };
        let kind = match t.inputs.m {
            Some(1) => HankelKind::First,
            Some(2) => HankelKind::Second,
            _ => panic!("{}: unknown m", t.label),
        };
        let n = t.inputs.n as usize;

        let result = hankel_seq(kind, fnu, z, n, scaling)
            .unwrap_or_else(|e| panic!("{}: unexpected error {:?}", t.label, e));

        let cy_re = t.outputs.cy_re.as_ref().expect("missing cy_re");
        let cy_im = t.outputs.cy_im.as_ref().expect("missing cy_im");

        for j in 0..n {
            let sub = if n > 1 {
                format!("{}[{}]", t.label, j)
            } else {
                t.label.clone()
            };
            assert_complex_rel(&sub, result.values[j], cy_re[j], cy_im[j], FORTRAN_TOL);
        }
    }

    eprintln!(
        "  besh_large_order: {} test cases passed (tol={:.0e})",
        tests.len(),
        FORTRAN_TOL
    );
}

// ── Test: Large-order I function (ZBUNI via ZBINU/ZBESI) ──

#[test]
fn besi_large_order_vs_fortran() {
    let refs = load_refs();

    let tests: Vec<&RefTest> = refs
        .tests
        .iter()
        .filter(|t| t.function == "zbesi" && t.outputs.ierr == Some(0))
        .collect();

    assert!(!tests.is_empty(), "no zbesi large-order tests found");

    for t in &tests {
        let z = Complex::new(t.inputs.z_re, t.inputs.z_im);
        let fnu = t.inputs.fnu;
        let scaling = match t.inputs.kode {
            1 => Scaling::Unscaled,
            2 => Scaling::Exponential,
            _ => panic!("{}: unknown kode", t.label),
        };
        let n = t.inputs.n as usize;

        let result = besseli_seq(fnu, z, n, scaling)
            .unwrap_or_else(|e| panic!("{}: unexpected error {:?}", t.label, e));

        let cy_re = t.outputs.cy_re.as_ref().expect("missing cy_re");
        let cy_im = t.outputs.cy_im.as_ref().expect("missing cy_im");

        for j in 0..n {
            let sub = if n > 1 {
                format!("{}[{}]", t.label, j)
            } else {
                t.label.clone()
            };
            assert_complex_rel(&sub, result.values[j], cy_re[j], cy_im[j], FORTRAN_TOL);
        }
    }

    eprintln!(
        "  besi_large_order: {} test cases passed (tol={:.0e})",
        tests.len(),
        FORTRAN_TOL
    );
}

// ── Test: Large-order J function (ZBUNI via ZBINU/ZBESJ) ──

#[test]
fn besj_large_order_vs_fortran() {
    let refs = load_refs();

    let tests: Vec<&RefTest> = refs
        .tests
        .iter()
        .filter(|t| t.function == "zbesj" && t.outputs.ierr == Some(0))
        .collect();

    assert!(!tests.is_empty(), "no zbesj large-order tests found");

    for t in &tests {
        let z = Complex::new(t.inputs.z_re, t.inputs.z_im);
        let fnu = t.inputs.fnu;
        let scaling = match t.inputs.kode {
            1 => Scaling::Unscaled,
            2 => Scaling::Exponential,
            _ => panic!("{}: unknown kode", t.label),
        };
        let n = t.inputs.n as usize;

        let result = besselj_seq(fnu, z, n, scaling)
            .unwrap_or_else(|e| panic!("{}: unexpected error {:?}", t.label, e));

        let cy_re = t.outputs.cy_re.as_ref().expect("missing cy_re");
        let cy_im = t.outputs.cy_im.as_ref().expect("missing cy_im");

        for j in 0..n {
            let sub = if n > 1 {
                format!("{}[{}]", t.label, j)
            } else {
                t.label.clone()
            };
            assert_complex_rel(&sub, result.values[j], cy_re[j], cy_im[j], FORTRAN_TOL);
        }
    }

    eprintln!(
        "  besj_large_order: {} test cases passed (tol={:.0e})",
        tests.len(),
        FORTRAN_TOL
    );
}

// ── Test: Large-order Y function ──

#[test]
fn besy_large_order_vs_fortran() {
    let refs = load_refs();

    let tests: Vec<&RefTest> = refs
        .tests
        .iter()
        .filter(|t| t.function == "zbesy" && t.outputs.ierr == Some(0))
        .collect();

    assert!(!tests.is_empty(), "no zbesy large-order tests found");

    for t in &tests {
        let z = Complex::new(t.inputs.z_re, t.inputs.z_im);
        let fnu = t.inputs.fnu;
        let scaling = match t.inputs.kode {
            1 => Scaling::Unscaled,
            2 => Scaling::Exponential,
            _ => panic!("{}: unknown kode", t.label),
        };
        let n = t.inputs.n as usize;

        let result = bessely_seq(fnu, z, n, scaling)
            .unwrap_or_else(|e| panic!("{}: unexpected error {:?}", t.label, e));

        let cy_re = t.outputs.cy_re.as_ref().expect("missing cy_re");
        let cy_im = t.outputs.cy_im.as_ref().expect("missing cy_im");

        for j in 0..n {
            let sub = if n > 1 {
                format!("{}[{}]", t.label, j)
            } else {
                t.label.clone()
            };
            assert_complex_rel(&sub, result.values[j], cy_re[j], cy_im[j], FORTRAN_TOL);
        }
    }

    eprintln!(
        "  besy_large_order: {} test cases passed (tol={:.0e})",
        tests.len(),
        FORTRAN_TOL
    );
}

// ── Test: Wronskian identity at large order ──
// I_v(z) * K_{v+1}(z) + I_{v+1}(z) * K_v(z) = 1/z

#[test]
fn wronskian_ik_large_order() {
    let test_cases: Vec<(f64, Complex<f64>)> = vec![
        (100.0, Complex::new(50.0, 30.0)),
        (90.0, Complex::new(40.0, 20.0)),
        (100.0, Complex::new(1.0, 10.0)), // region 2
    ];

    for (fnu, z) in &test_cases {
        let i_result = besseli_seq(*fnu, *z, 2, Scaling::Unscaled)
            .unwrap_or_else(|e| panic!("I_{fnu}({z}): {e:?}"));
        let k_result = besselk_seq(*fnu, *z, 2, Scaling::Unscaled)
            .unwrap_or_else(|e| panic!("K_{fnu}({z}): {e:?}"));

        let iv = i_result.values[0];
        let iv1 = i_result.values[1];
        let kv = k_result.values[0];
        let kv1 = k_result.values[1];

        // Wronskian: I_v * K_{v+1} + I_{v+1} * K_v = 1/z
        let wronsk = iv * kv1 + iv1 * kv;
        let expected = Complex::new(1.0, 0.0) / z;
        let err = (wronsk - expected).norm() / expected.norm();
        assert!(
            err < 1e-12,
            "Wronskian I·K at fnu={fnu}, z={z}: rel err = {err:.2e}"
        );
    }

    eprintln!(
        "  wronskian_ik_large_order: {} test cases passed (tol=1e-12)",
        test_cases.len()
    );
}
